### ISSUE TITLE
Add Bandwidth/Thoughput Limits

### ISSUE THREAD

**Issue by super3** [Storj/storjshare-gui#117]
For Test Group C we test bandwidth and throughput. Because some users might have limits, we need to also have these limits in the GUI. 

- [ ] @boshevski Prototype design for bandwidth/throughput limits
- [ ] @MrFancyMonocle  Implement design in GUI
- [ ] @gordonwritescode Hook up GUI to storjshare-gui

**Comment by bookchin** [comment]
Seems to me that this would cause more issues than it would solve. I'd think users should be responsible for limiting bandwidth at the router level if that's something they need to do.

Since we aren't actually doing a Test Group C (in regard to performing just dumb bandwidth testing), I can't see StorjShare GUI users really eating up that much of their bandwidth by simply participating in the network and serving shards to renters.

Generally the most bandwidth is going to be consumed by farmers that are public with high availability due to a higher likelihood of them receiving more contracts.

I'm going to close this. If you really think it's important, reopen it and we can talk about it.

**Comment by super3** [comment]
@bookchin This is the most requested user feature, and I think it should be implemented. That being said I agree with your current assessment. The current GUI does not use enough bandwidth to be significant. Therefore, we don't really need implement it now and it could be months before we actually need to. There are also other applications and router settings you can use to do this outside of the GUI, if a stopgap measure is needed.
