### ISSUE TITLE
Auto Updates

### ISSUE THREAD

**Issue by boshevski** [storj/storjshare-gui#222]
http://electron.atom.io/docs/api/auto-updater/

**Comment by super3** [comment]
@gordonwritescode Need some feedback on the plan for updates. I believe we were heavily against automatic updates for the app itself, but may want to auto-update some of the dependencies. I don't remember all the pros and cons from our discussion so please educate us.

**Comment by bookchin** [comment]
@phutchins can you take a look at @boshevski's link above and see what it would take to set up https://github.com/ArekSredzki/electron-release-server ?

**Comment by bookchin** [comment]
Also: https://github.com/GitbookIO/nuts

**Comment by super3** [comment]
@bookchin @aleitner @phutchins What is our priority for this issue? Its and undertaking, but has some major benefits in the short/long term.

**Comment by bookchin** [comment]
Low relative to everything else.

**Comment by phutchins** [comment]
I say as long as we don't doing too many more breaking change updates before it's done, I say high but not highest. I do think it's fairly important due to the fact that getting some of these major bug fixes out into the network faster is pretty valuable.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
