### ISSUE TITLE
Add support for unpaid balance

### ISSUE THREAD

**Issue by felixbrucker** [Storj/storjshare-gui#262]
### Feature
In TGC and the final launch it might be useful to see your "pending" earnings from farming as **unpaid balance**. This gives a better overview of the currently "farmed" amount of SJCX that has not been paid yet.
It might be desirable to add this feature at a lower level so cli users, too, can get this data somehow (an api call maybe).

**Comment by super3** [comment]
Thanks for the feature request. To start this will be calculated and posted at the end of the month, then calculated daily (still paid at the end of the month), and when we bring micropayments online there will be no unpaid you will actually get paid instantly. 

Closing this for now. Best case, we don't need this because of micropayments, and worst case this will be integrated later once we have an API to display that.
