### ISSUE TITLE
Rework UI

### ISSUE THREAD

**Issue by bookchin** [Storj/storjshare-gui#266]
* Don't show the live log - use @aleitner's #265 to just write the log to a file (this may also solve our memory issues)
* Show only important status indicators like:
  - Last message received time
  - Connected peers
  - Space used
  - Last successful contract completed
  - SJCX balance
  - Link to open logfile

**Comment by super3** [comment]
This should stop a ton of bug reports from normal operation.

**Comment by 1credit** [comment]
Would like to add a few other features:

1)  Display total rented space, not just free space.
2)  Keep and display basic "health" metrics like timeout percentage, ideally over a couple of timeframes (since start, last week, last day, last hour???)
3)  Have the update function actually launch an upgrade vs. sending us to a website
