### ISSUE TITLE
Fix code coverage instrumentation and add tests for the renderer

### ISSUE THREAD

**Issue by bookchin** [Storj/storjshare-gui#267]

**Comment by MrFancyMonocle** [comment]
I can never support tests in any UI code, until it's reached a certain level of maturity: the amount of code rewrite is simply too great with the frequency of tweaks anyone would do, until at least several iterations into a design. Until then, quick and sometimes buggy iterations are favorable to me. That, and unit testing would have caught zero of the bugs that I've fixed recently; most UI bugs tend to crop up around the framework DSL eco-system, and aren't things you'd even want to write test cases for. Common sense over coverage here: just don't block anything because there isn't a test, at least not yet.

**Comment by bookchin** [comment]
From the research I initially did to determine how to instrument the code for coverage without electron, it's not trivial and I agree about the extent of it's utility for this particular package.
