### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by matanbr** [Storj/storjshare-gui#270]
On last version 0.8.9 when hitting View>Reload I am getting this error message
![default](https://cloud.githubusercontent.com/assets/9035057/16678136/f33036a8-44e4-11e6-9b2e-ce69f28ee3c5.png)

**Comment by littleskunk** [comment]
Last GUI release we updated the electron version. The old version was printing out a warning. reloadIgnoringCache is depricated. The new electron version removed the depricated function.

**Comment by Blackwolfen** [comment]
the javascript error makes it unable to restart the gui as it crashes
so if you get the black screen of death you cant restart it with the restart because of the javascript error

**Comment by strutzu** [comment]
I've got update the latest GUI version,let it running for 2 hours after that I get a white screen ,  when I try to reload from "View -> Reload " I got the same message error like matanbr have mentioned in the upper comment.Need to quit,and start again the GUI.

**Comment by allx1** [comment]
![storj](https://cloud.githubusercontent.com/assets/17143942/16697718/5abf2d7c-454b-11e6-824e-85a7471602bc.JPG)

**Comment by littleskunk** [comment]
@allx1 move that screenshot to a new issue please. It has nothing to do with the javascript error.

**Comment by allx1** [comment]
when I try to Reload the Storj Share I will get the Javascipt error....
My previous post was moved here and it was quite simmilar issue.
![storj_2](https://cloud.githubusercontent.com/assets/17143942/16699216/25ab8074-4553-11e6-936b-27e3b3bdf7ba.JPG)

**Comment by bookchin** [comment]
We just need to remove the reload button - it only reloads the GUI, but does not reset the farmer process or any other state. It's useless and confusing.

**Comment by littleskunk** [comment]
@bookchin I am not sure we should remove it. The reload button was a fast way to reload everything without quit and restart the app. As far as I could see even the farmer process was restartet. Pressing the Stop and Start button cause an error because leveldb was still in use. The reload button was working without any error message.

The meanwile I uploaded a little hoftix. I hope everyone can farm without to many crashes until mondy.
Hotfix:
https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.info.exe
Same loglevel as the normal GUI release but the reload button is working.

https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.warn.exe
Reduced logging. This version will crash a few hours later. Watch for `Contract no longer open for offer` to be sure it is running fine.

https://github.com/Storj/storjshare-gui/releases/download/v0.8.9/storjshare-gui.loglevel.off.exe
No logging. This version should not crash and run for days. You can only look into your shard directory to see if it is running fine.

**Comment by littleskunk** [comment]
Fixed with v0.9.1
