### ISSUE TITLE
White screen of death with logging enabled under version 1.0.0

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#288]
Just to test, I set logging to "Show All Information" and had the WSoD in under an hour.  Trying now with "Show Warnings and Errors".

For what its worth, I had 165GB free on the %appdata% drive.  I have cranked up a resource monitor window as well so will be able to report on memory usage if it reoccurs.

Zipped log file attached.

[Drive-0_2016-7-20.zip](https://github.com/Storj/storjshare-gui/files/374957/Drive-0_2016-7-20.zip)

**Comment by 1credit** [comment]
Interesting to note memory growth after startup as it read through each shard, once writing started, it appears memory usage is stable.

http://puu.sh/q8N5L/0dc588af39.png

**Comment by 1credit** [comment]
Primary process died shortly after it exceeded 1GB of memory usage.  The two smaller processes remained running.  Restarting with logging disabled.

Growth from ~110mb to 1GB took about an hour at "Show Warnings and Errors".  Panel is reporting 22.836GB of shards.

**Comment by 1credit** [comment]
Sample after running for about 10 minutes and starting out around 100mb of memory:

http://puu.sh/q8O6y/fe77ec7df2.png

**Comment by 1credit** [comment]
Possibly related:  The process seems to be constantly reading shards - its been doing so at around 50MB/Sec since starting up with only around 1mbit/sec of network traffic - essentially maxing out the supporting harddrive (based on their being a queue to them).

http://puu.sh/q8Pvo/6429f86025.png

**Comment by 1credit** [comment]
Repeated a White Screen of Death upon process reaching a Windows memory commit footprint of 1GB.

http://puu.sh/q8Q3L/5a1508f7d8.png

Of note,:commit grew regularly until that point but fluctuated for a few moments once there, dropping below, hitting the limit, dropping below, a few times prior to death.

**Comment by WilhelmGGW** [comment]
GUI 1.0.0 Windows: I get**White Screen of Death** even with logging turned off! 

AND Updates on two computers have not stopped reading hard drive in over two hours! The drive light has not even flickered!

**Comment by 1credit** [comment]
@wilhelmGGW - seeing exactly the same things, details above your post.  Thanks for the confirmation I'm not alone.

**Comment by subwolf** [comment]
You broke it!

**Comment by littleskunk** [comment]
@bookchin Looks like the contract count is the new out of memory problem.

**Comment by 1credit** [comment]
@bookchin Understand the contract count - that is really cool presuming it can be calculated without having to read every existing shard.  What is the Connected Peers suppose to be showing, in netstat -n terms please?

**Comment by bookchin** [comment]
@1credit connected peers is the number of contacts in the routing table - it's not related to actual "connections" as nodes do not keep connections open to their peers.

The contract count *is* the source of this problem and I did suspect this was going to be an issue. There are only two ways to implement count with LevelDB:

1.) Read the entire dataset (what we are doing now)
2.) Implement an application layer on-write counter

See: http://stackoverflow.com/questions/13418942/how-to-get-the-exact-number-of-keys-in-leveldb-fast

We need the former implemented for shard reaping (we are reusing the same iterator code to count contracts), but the latter is going to be the only way to do this efficiently. Furthermore, the metric should actually be *shard* count, as multiple contracts can be held for a single shard and we are only reading the keys - not the contents.

I'll have to solve this by adding some event triggers to `StorageAdapter` or `Manager` that the application can use to increment or decrement a counter to avoid re-reading the entire dataset. However, we will _still_ need to read the entire dataset once to get the initial shard count, but I think the real issue here is not the full read itself, but the frequency and possible overlap of those full reads (currently every 3 minutes by default).

**Comment by 1credit** [comment]
Confirmed via folder properties that I have approximately 21.4GB of shards in something like 11,592 files.  GUI is reporting 22.836 GB which is a bit high presuming the GUI's number is base 2 like Windows is and not base 10.  Hmmm...  guess that is the source of that difference:  21.4 in 1024 byte units is 22.98 in 1000 byte units - but that is another issue.

Although I can't say I'd be happy with the GUI reading ALL of the shards, it should be able to read 21GB in 10 minutes or so, but currently has not finished in over an hour.   Based on what your saying, a 3 minute full read of the database is, well, insane (my math was based on 50mb/sec read speeds, perhaps a bit slow, perhaps not with all the windows open/close/file fragmentation seeking overhead).  Although perhaps debatable for 10gb or 20gb, the issue is clearly non-sustainable if my full 2 TB space allocation was used.

Remember also this is typically going to be running on someones home PC, with the assumption it will be a fairly benign background tasks.  Beating the disk to death every few minutes is not benign.  Seriously impact some gamers ability to play and you will lose access to some of the biggest, fastest, best built PCs out there.   

Oh, and then, of course, there is the memory leak associated with doing it <smile>.

Just my 2 cents.

**Comment by bookchin** [comment]
Yes we measure with 1024 units and use LevelDB's `approximateSize` to determine the size (which may not include recently written data).

I may not have been clear about the 3 minute interval.I certainly was not suggesting that the read would complete in that time - I was suggesting the opposite. That the interval to start the read was set to 3 minutes, which would in many cases not complete before the read was started again - causing the massive diskfuckery.

All of this aside, there simply is no way to count the shards without performing a full read of the dataset *at least once*. This is what I'm working on now: read the dataset once and then catch `add`, `update`, and `delete` events that I'm adding to the `StorageAdapter` to update a cached counter so that we can still display that metric.

The memory leak is related to overlapping full reads of the dataset, which keep the read keys in memory. I'm working on it.

**Comment by WilhelmGGW** [comment]
bookchin,
Re: The disparity with the unit size in reporting Space Used - *vis a vis*, the Windows reporting standard

I think this is going to be an issue that forum helpers are going to be explaining time and time again to our huge future universe of Windows GUI farmers. I check and record my farmer.db folders for size and shard count, every day. So I noticed this disparity right away when I started running the new version. I was *Alarmed!* when I the GUI registered more Space Used than space I had allocated -- on a couple of nodes that have already filled to my allocation limit. The panic was that, "StorjShare is ignoring my allocation and is going to run unrestrained to fill my whole hard drive!"

Now that you explain it here, that was an unwarranted panic, to be sure. However, non-techie that I am, the panic was there, and perhaps to be suffered not infrequently by new Windows users. Perhaps leading some to jump ship and discontinue renting space to Storj.

**Comment by super3** [comment]
@WilhelmGGW Optimization we can add in the future. We have over 1,000 reporting farmers and PBs of free space. If a couple jump ship that is OK. Need to prioritize getting people using the platform over optimizations.

Because of the massive amount of farmers on the network, I don't see us hitting anyone limits anytime soon unless they are running it on a flash drive.

**Comment by 1credit** [comment]
Subwolf requested a full log be collected, which I launched before going to work.  Just got home and am posting via this comment.
[Drive-0_2016-7-21.zip](https://github.com/Storj/storjshare-gui/files/377155/Drive-0_2016-7-21.zip)
