### ISSUE TITLE
GUI 1.0.1 observations/potential issues

### ISSUE THREAD

**Issue by 1credit** [Storj/storjshare-gui#294]
1)  During the "Counting Shards" phase access to the other menu items, like logging level, is blocked.
2)  With 22GB of existing shards, "Counting Shards" phase lasted a bit under 10 minutes on a 2 drive Windows stripped array (Toshiba DT01ACA300's (7600 RPM SATA 6GB/s 64MB Cache drives - e.g. Typical).  While visually monitoring via Windows Resource Monitor, disk activity from the (3) Storj Share.exe processes varied from 2mb/s-24mb/s in total.
3)  Projecting those speeds to the full 2TB currently being offered would predict a 13ish hour "Counting Shards" phase.  Doubt if that would be acceptable to anyone beyond hard-core users.
4)  While counting shards, connections were enabled (10 were established)
5)  An unexpected amount (call its 15%) of I/O activity during the counting phase was shard writing.   Apparently new contracts were being accepted during the counting phase.
6)  After running about 25 minutes, memory seems stabler than in 1.0.0 at about 116MB (up from a launch amount of around 100MB). however I'm seeing it slowly grow (like up 6MB while typing this line).

#3 and #6 may be concerns.  #1 is an inconvenience.  Full logging is occurring in case of another crash.

**Comment by bookchin** [comment]
1. You should be able to dismiss the modal by click outside it
2. I can't really speak to disk speed, it should go as fast as it can
3. Yeah it sucks if you already have a lot of contracts, but we don't have many options for displaying that metric. We have to do a full retroactive count once. This isn't a problem for new drives. 
4. Yeah we aren't halting the farmer during this process, but I don't imagine we have any reason to do so. 
5. Log level set to full is writing a shit ton of debug messages to your logfile, so I imagine that's why.
6. A lot of that RAM is being used by electron, to get an idea of what's being consumed by the application code, subtract the average RAM usage that chromium uses (electron is just a chromium shell), I'd be interested in the result

**Comment by 1credit** [comment]
#1 Tried, didn't work - wanted to reduce logging level and couldn't get there.
#3 If by "Once" you mean once per the life of the drive, that is fine.  If "Once" means once per restart of the application - that is much less good.  Hmmm, time to test.   Apparently its a Once per Life issue - very cool.
#5 My original thought until Resource Manager showed me the filenames - and they were all shards.
#6 About an hour and a half after launch, RAM usage is roughly the same.  Here is hoping the leaks are plugged!
