### ISSUE TITLE
Invalid Storage Size Error

### ISSUE THREAD

**Issue by stricq** [Storj/storjshare-gui#427]
### Versions

Replace the values below with your own:
- **GUI Version:** v2.0.16
- **Operating System:** Windows 10
### Expected Behavior

Please describe the program's expected behavior.

The program should start up and run all shares automatically after installation/upgrade or after a reboot.
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

After an installation/upgrade or reboot, the "Invalid Storage Size" error occurs.  Clicking on Start Share elicits the same error.  The program must be shutdown and restarted manually.  After the manual start, the program starts all shares properly and continues to run properly.
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Install/Upgrade to a new version of Storj, or
2. Reboot your computer
3. Fairly certain that "Launch Storj Share at user Login" and "Share previously running drives at launch" must both be enabled.

**Comment by littleskunk** [comment]
I assume you are using a network drive that is not connected on user login and needs a few more seconds. What do you expect us to do in that case? I don't see a way to fix that windows problem.

**Comment by digidan** [comment]
This was happening for me, and the shared drives weren't showing up in the storj app selector to choose them as a drive.  I had to unmap then remap the drives, and eventually just use the network locations instead.  It wasn't happening in previous versions just in the last few.

**Comment by stricq** [comment]
Sometimes it happens when I just start up the program, even when the OS has been running for days.  Right now it's refusing to start with this error over and over.  v3.0.1

**Comment by stricq** [comment]
Even with the logging set to Debugging Mode, only one line of logging is created and that is the "Log file created." line.

**Comment by stricq** [comment]
If more information is needed, then let me know where to debug the code.  Since there is no logging and nothing on the command line, debugging is the only option left.

**Comment by stricq** [comment]
I've already tried both of those things.  Neither makes any difference.

**Comment by littleskunk** [comment]
That is a windows problem as well. Storage on the drive is greater than total file size.
![screenshot](https://cloud.githubusercontent.com/assets/6333390/20590854/d7bafe7c-b225-11e6-9338-4366ae873653.jpg)

Reduce the available space and everything is fine. Based on my screenshot I would reduce my space 1%. That should work until my drive is full.
Note: It depends on the file system and different windows features. In your case it could be a greater difference. Please calculate it yourself.

**Comment by stricq** [comment]
You sure are quick to assign issues in your program to Windows.  I know Windows has it's issues, but this is clearly a problem in your program whether you acknowledge it or not.

**Comment by littleskunk** [comment]
It is clearly a problem in our program? If you have a good idea how to fix this windows problem please go on. Please open a new issue and write down your idea. We will try to implement it. Please try to understand us. Calculating the windows overhead and reducing the available space is not that difficult.

**Comment by zugnugz** [comment]
I know what causes this. Mapped network drives are tied to the user that account that makes the drive. So if another program, such as the nullsoft installer, runs as Adminstrator then when it starts storjshare-gui that program will be ran "as adminstrator" so it too will fail to see the network drives.

Try this: run cmd.exe .... 
In the DOS window type: net use T: \\YourServer\ShareNameExample 
t:
dir

Okay now Open cmd.exe (as administrator), type: T: it will fail. Administrator fails to see your T: drive because administrator doesn't have the token. Basically it's way of sandboxing shares from  other users.
You can over ride this with a registry hack:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\

EnableLinkedConnections DWORD flag to 1
<<and then reboot Windows for the setting to take effect>>

I too ran into this bug today, and I realized I had seen it before running my steam games off my network share. The installer scripts in steam would fail to run the installers for the C++ runtimes or DirectXSDK for some library the game used.
