### ISSUE TITLE
GUI 5.0.0 Step 3 go back to Step 2 will not remember Storage Location

### ISSUE THREAD

**Issue by littleskunk** [storj/storjshare-gui#521]
### Expected Behavior

Select a valid storage location and go to step 3.
Go back to step 2.
I would expect my old storage location.

### Actual Behavior

Storage location is empty.

**Comment by tempestb** [comment]
This is also true of the SJCX address.  

In fact, if you change the drive and don't go back to the SJCX tab, and then try to submit on the final tab, it will complain that the SJCX address is missing.  So basically, if you get any error, you have to start over again from tab 1.  (In my experience)

**Comment by JukeboxRhino** [comment]
I don't think this is possible. For security reasons, you're not allowed to set the contents of a file input in javascript, otherwise you could set it to secret files and upload them without user knowledge. When you navigate away from that step, that page is destroyed by Electron and the input element along with it. When you click the back button, it has to re-create that page with a fresh input element. I've already implemented autofilling for most input boxes in the wizard but I'm afraid autofilling an file input element just isn't possible.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
