### ISSUE TITLE
Provide a Universal Windows Platform Package (UWP - appx) release for testing

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-gui#535]
Please convert the Windows 64-bit release of the storjshare-gui exe to an appx file using the code signing cert for Storj Labs.

Overview of UWP:
https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide

Overview of the Bridge:
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root

How to:
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter

Down the road if you like this type of app, fully migrate the application over to an appx to provide even more capabilities.

Windows 10 Anniversary Update (10.0.14393.0 and later) Pro or Enterprise edition.
64 bit (x64) processor
Hardware-assisted virtualization
Second Level Address Translation (SLAT)
Windows Software Development Kit (SDK) for Windows 10. (https://go.microsoft.com/fwlink/?linkid=821375)

In Windows Program and Feature / Add Windows Components, select Containers

Download and install the converter app
https://aka.ms/converter

Download a base image that your OS runs on (recommend running on Windows 10 Creators 1607)
https://aka.ms/converterimages

Launch the Convert app
Run Set-ExecutionPolicy bypass
Run DesktopAppConverter.exe -Setup -BaseImage .\BaseImage-1XXXX.wim -Verbose

Then convert the app and prepare it for the Windows Store
DesktopAppConverter.exe -Installer C:\Installer\MyAppSetup.exe -InstallerArguments "/S" -Destination C:\Output\MyApp -PackageName "MyApp" -Publisher "CN=MyPublisher" -Version 0.0.0.1 -MakeAppx -Sign -Verbose -Verify

Let me know with questions

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
