### ISSUE TITLE
invalid storage size

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#546]
Allot of farmers are getting the `invalid storage size` error when migrating from the GUI v4.x , is this a bug?

**Comment by MeijeSibbel** [comment]
It appears that a restart of storjshare solves the issue and picks up the node that was giving the error. So there is something wrong in the code probably

**Comment by littleskunk** [comment]
It is a feature. The old GUI accepted invalid allocated drive space. You could farmer 8TB on a 100GB drive. The new GUI validates the allocated drive space.
throw error if allocated drive space > used space + free space

Reduce the allocated drive space and everything will work as expected.

**Comment by sschutte** [comment]
Would it be sufficient to modify the following entry in the ```settings.json``` file?

```
 "path": "D:\\",
        "size": "999",
        "unit": "GB",
```
The above is the original settings file, I reduced the size to 997 and 995, saved it and tried the import again but I get the same error message. 

Pretty sure I am missing something obvious, would be happy for any pointers.

**Comment by sschutte** [comment]
Solved it now.

For any others that might run into the same issue, here are the steps I used to work around this.

* The original ```settings.json``` file first needs to be encoded to UTF-8 without BOM otherwise the import fails.
* Once the import works, the gui prompts the user to convert the old settings into a newer format.
* What happens next is that two files are generated with the ```id``` of the disks. 
* These files now have to be individually edited: 
```
"storageAllocation": "927GB",
```
Here a person just has to try and see what works by reducing the size, running the import again and see if the storj-client does'nt complain about invalid storage size.

Not a very smooth upgrade process but at least my nodes are up and running again.

**Comment by littleskunk** [comment]
Calculating the correct storage size is not that difficult. It has nothing to do with the migration. If you setup a new farmer you would run into the same problem.

Next time try this to get the correct free size:
Windows - `wmic logicaldisk get size,freespace,caption`
Linux - `df -k`

**Comment by sschutte** [comment]
Maybe this information could be added to the new Storjshare-GUI_V5 on Google docs which is currently being written under the section ¨common migration errors¨
