### ISSUE TITLE
GUI v5.0.0 running prevents the system to restart or shutting down

### ISSUE THREAD

**Issue by HuhnSolo** [storj/storjshare-gui#550]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** OSX 10.11.6

### Actual Behavior

Storj running prevents the system to restart or shut down. Have Storj to end manually.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
