### ISSUE TITLE
GUI 5.0 uninstall does not remove personal data when checked

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-gui#557]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10 Enterprise - 64-bit

### Expected Behavior

Please describe the program's expected behavior.

```
When you uninstall Storj Share and check remove personal data then it should remove the folder placed in %APPDATA%\Storj Share
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When you uninstall and check the box remove personal data %APPDATA%\Storj Share is not removed
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install Storj Share GUI 64-bit 5.0
2. Uninstall Storj Share GUI and check remove personal data

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by computeronix** [comment]
It also does not remove the folder/files %USERPROFILE%\.config

**Comment by computeronix** [comment]
Also the application does not exit upon uninstall.  It should quit/exit the process at the start  of the uninstall process.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
