### ISSUE TITLE
Start when Drive already started causes restart of node (GUI 5.0)

### ISSUE THREAD

**Issue by computeronix** [storj/storjshare-gui#559]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0
- **Operating System:** Windows 10 - 64-bit

### Expected Behavior

Please describe the program's expected behavior.

```
When a drive is started the gear next to it should have Start greyed out since it is already starting
Likewise, when Stopped, the Stop button should be greyed out (not selectable) as its already stopped
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When a drive is already started, you can click Start in the gear and it issues a restart of the node
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start a drive
2. Click the gear -> Start

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
