### ISSUE TITLE
Windows - App doesn't start minimized.

### ISSUE THREAD

**Issue by ghost** [storj/storjshare-gui#564]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
When my PC starts i expect app to be minimized into the tray like all previous versions.

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
pc startup opens up storj share dashboard.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... obvious
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by MrFancyMonocle** [comment]
The current workaround is to add the application to the list of startup applications in the way provided by the Operating System in use, but it was a nice-to-have setting; tagging as feature to add, but it's lower priority as of the time of this post.

**Comment by computeronix** [comment]
Windows Suggestion:

--Add an advanced option to allow automatic start on login   (system start is not available to happen yet as all the data (%APPDATA%) sits under the user whom configured it and not in the system configuration

--Also add an option to start minimized

Windows Implementation:

Add a registry key when checked under
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run

if the key explorer / run does not exist then create it

Create a String and with the Name 1  (or whatever is next in the list as it is incremental depending on what else auto starts up
Value -> %PROGRAMFILES%\Storj Share\Storj Share.exe  or %PROGRAMFILES(x86)%\Storj Share\Storj Share.exe

depending on 64-bit or 32-bit  binary

**Comment by computeronix** [comment]
Not recommended (regarding Security) but if you dont care you can turn on auto login on startup when combined with the above information will essentially auto start Storj on reboots/startup

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon

Create a few String keys below
DefaultUserName  -> yourusername
DefaultPassword -> yourpassword
AutoAdminLogin -> 1

**Comment by theoob** [comment]
My workaround is to use this batch file, which I've put in shell:startup. It starts Storj, waits 8 seconds for it to load, then minimizes it. You will need NirCmd in your system path, which you can find here:
http://www.nirsoft.net/utils/nircmd.html

Batch file is as follows:
```
start "" "C:\Program Files\Storj Share\Storj Share.exe"
ping -n 8 127.0.0.1>nul
nircmd win min class Chrome_WidgetWin_1
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
