### ISSUE TITLE
Had 4 disks. Rebooted only 3 disks needed to add 4th again GUI 5.0

### ISSUE THREAD

**Issue by Steamon** [storj/storjshare-gui#565]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.0
- **Operating System:** Windows 10 creator update.

### Expected Behavior

I expect the program to remember my disks when rebooting.

### Actual Behavior

I rebooted my computer after waking up and had only 3 disks instead of 4 disks. 

### Steps to Reproduce

I will see tomorrow again after restart if I have 3 or 4 drives. It's important to report this because it can happen maybe on bigger farms.

**Comment by Steamon** [comment]
It happend again when I rebooted my computer can this by looked at? Thanks.

**Comment by jfnz** [comment]
Same here

**Comment by adwit3** [comment]
I had this same bug, on old gui i have 3 drives, after update gui to 5.0.1 and import config I still have 3 drives, but after restarting gui i have only 2 drives. Why? But I have 1 core 2 thread cpu, so 1 drive=1 cpu thread

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
