### ISSUE TITLE
One node not completly started (visual bug)

### ISSUE THREAD

**Issue by tross2015** [storj/storjshare-gui#567]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **VM win 10 pro 10 virtual processors 6gb ram 

### Expected Behavior
All nodes start and show status 

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```All nodes start and show status except one.
log from effected node is normal 
![vmbug](https://cloud.githubusercontent.com/assets/20988413/25772576/ad76226c-326e-11e7-826f-f6d68ac7d34a.PNG)
![vmbug](https://cloud.githubusercontent.com/assets/20988413/25772582/e782d4b4-326e-11e7-8cbf-1fd81c6a36db.PNG)
![logt](https://cloud.githubusercontent.com/assets/20988413/25772598/57d27c74-326f-11e7-9875-897ce3c4e6fb.PNG)




```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...VM 10 virtual processor 6gb ram Host 16 threads (2cpu)  24gb ram 
2. ...2 x win 10 pro and hyper v
3. ... Start Sorj

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by tross2015** [comment]
![logt](https://cloud.githubusercontent.com/assets/20988413/25772608/88026f58-326f-11e7-891b-f95b5435f677.PNG)
![errorbild](https://cloud.githubusercontent.com/assets/20988413/25772613/95c9d4e6-326f-11e7-9eae-62c83c21f50f.PNG)

**Comment by tross2015** [comment]
This is after restarting a couple times. On the first try I waited an hour! Looking at the log it seems just to be a visual bug.

**Comment by tross2015** [comment]
It happens on the host too that has 16 threads 24gb
![hoster](https://cloud.githubusercontent.com/assets/20988413/25781379/bb376ade-3339-11e7-9b22-969144ed3546.PNG)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
