### ISSUE TITLE
Update 5.0.1 did not import all drives

### ISSUE THREAD

**Issue by SkyCrypto** [storj/storjshare-gui#575]
### Versions

Replace the values below with your own:

- **GUI Version:** 5.0.1
- **Operating System:** Windows 7 professional

### Expected Behavior

Please describe the program's expected behavior.
Update to 5.0.1...transfer of settings and data
```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```I did the update to 5.0.1.  Imported the settings.json file but only two of my three drives showed up.  How do I make sure the third one gets added and not loose the data that was shared on there and my credit for sharing it?

I also do not see where to confirm the payout address that used to be displayed in the older version.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
