### ISSUE TITLE
EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-gui#604]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
catches a critical error and gives the user feedback on this error.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
returns a critical error, for reference:

https://github.com/atom-community/autocomplete-paths/pull/16
https://github.com/shelljs/shelljs/issues/514
https://github.com/npm/npm/issues/13461

As reference from the issue above, users have reported bypassing this issue in the following way:

1- Launch Storj Share as administrator.
2- White-list storjshare in windows anti-malware or disable/uninstall Anti-Malware software.
3- try executing the following command in CMD as admin npm cache clean.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

![b4f7bbe8cfba4d49a0f76903679454c5](https://cloud.githubusercontent.com/assets/11735738/26524807/280e7b94-4338-11e7-9e07-00360df41df3.png)

**Comment by starrychloe** [comment]
Got this too, but for a log file, for the latest version.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
