### ISSUE TITLE
GUI installer doesn't gave a choice where GUI should be placed, always use the C: drive

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storjshare-gui#609]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.1.0
- **Daemon** 3.1.0
- **Core** 6.5.0
- **Protocol** 1.1.0
- **Operating System:** Windows 10 64x 1607

### Expected Behavior

Please describe the program's expected behavior.

```
When I start GUI 5.1.0 installer, I can choose the D: drive for GUI installation.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
When I start GUI 5.1.0 installer, I can't choose the installation drive, it's always use the C:
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start GUI install
2. Click Install button
3. StorjShare immediately start save all its files to the `c:\Program Files` without asking me, where i want it been installed.

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
