### ISSUE TITLE
Drive count is limited by CPU cores

### ISSUE THREAD

**Issue by bathrobehero** [Storj/storjshare-gui#613]
### Versions
GUI 5.1.0
Daemon 3.1.0
Core 6.5.0
Protocol 1.1.0
- **Operating System:** Win7 x64

### Expected Behavior

Handling unlimited amount of drives.

### Actual Behavior

After importing config of a bunch of drives and after restart there will only be 12 drives and the rest disappears. I have a 12 core processor and I'm pretty sure it's the reason considering that upon importing an older config it will say insufficient system resources for a couple of drives. But 40+ works completely fine.

### Steps to Reproduce

Import more drives than CPU cores you have
Restart

Edit: apparently it's intended:
    if (this.running >= cpus().length && !unsafeFlag) {
      return callback(new Error('insufficient system resources available'));
    }
which is silly and the unsafe flag doesn't work.

**Comment by littleskunk** [comment]
Doing stress tests we have noticed that farmer are going offline because they don't have the CPU power needed to run so many farmer. A second problem is the download speed. My farmer was uploading mirrors to 10KByte/s farmer.
At the moment we have a stable network on idle but as soon as we get some load we have a problem. That is why we had to implement this limit.

Please remove the additional farmer. The next protocol version will identify slow and underpowered farmer and a few updates later we will reduce the number of shards they can get.
