### ISSUE TITLE
[Feature request] Flashing notification for upgrades

### ISSUE THREAD

**Issue by nerdatwork** [storj/storjshare-gui#638]
### Versions

- **GUI Version:** v6.1
- **Operating System:** Windows 7

### Expected Behavior

A feature like flashing of GUI whenever there is any update. This feature could be implemented as:

1. Flashing the GUI till farmer takes note of it. This is helpful when farmer is working on something else and upgrade could have been applied many hours ago,

2. Showing a **marquee text** at the title of GUI next to Storj Share like "New Storj version available 6.2"

3. Desktop notification by a balloon on right or left hand bottom of the screen notifying that an update is available to be installed.

Any combination of these features along with some sound notification would be a great improvement.

### Actual Behavior
Right now the only way to upgrade is when farmer manually checks the GUI. Either a notification is shown or have to go to HELP and check for upgrades.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
