### ISSUE TITLE
Storj Share GUI Linux x64 drops shares

### ISSUE THREAD

**Issue by maxblazr** [storj/storjshare-gui#648]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.20
- **Operating System:** Linux mint 18.1 x64

### Expected Behavior

when the program is closed after creating a share, it should retain the share information upon relaunching

### Actual Behavior

after closing and re opening the program the shares are gone and it asks to create a new one. Every time. Started immediately after updating to 6.2.0

### Steps to Reproduce

1. open storj share
2. create new share
3. after connection is established close program
4. upon reopening it asks to create a new share, will not allow importation of old .json file

### Screenshots (Optional)

[configs.zip](https://github.com/Storj/storjshare-gui/files/1157343/configs.zip)
![2017-07-18-171650_1062x904_scrot](https://user-images.githubusercontent.com/21028921/28340833-2d2bcea4-6bdf-11e7-938a-a4b4bcc8ce8d.png)
![2017-07-18-171740_857x874_scrot](https://user-images.githubusercontent.com/21028921/28340830-2d220932-6bdf-11e7-84f1-791a922b6918.png)
![2017-07-18-171753_1003x878_scrot](https://user-images.githubusercontent.com/21028921/28340831-2d22b6e8-6bdf-11e7-9dc5-aafeb16af2b7.png)

[logs.zip](https://github.com/Storj/storjshare-gui/files/1157347/logs.zip)

**Comment by adamscarcella** [comment]
I'm having the same issue, but on Windows. I created my first Storj node in June of this year and have upgraded the storjshare-gui a few times since. However, this last time I upgraded, it could not load the configuration. 

![image](https://user-images.githubusercontent.com/1242159/28444865-13564f12-6d8e-11e7-95e5-3a861c9aa370.png)

![image](https://user-images.githubusercontent.com/1242159/28444875-25cf2876-6d8e-11e7-906f-8a2a1bb0ca8c.png)

I'm an experienced user, skip setup

![image](https://user-images.githubusercontent.com/1242159/28444885-375a58ae-6d8e-11e7-9fef-70a51ad4126c.png)

![image](https://user-images.githubusercontent.com/1242159/28444903-56b6edc0-6d8e-11e7-8bff-f9cd7bbad2f5.png)

I even tried to create a new config using the Wizard, but that failed in the same way.

I have over 10 GB shared on my drive already and I can't seem to tell Storj to use it again.

What can I do to restore my node? And if I lose this data (due to no fault of my own) does that mean I have to start over and not get Storj coins?

**Comment by MeijeSibbel** [comment]
could be related to https://github.com/Storj/storjshare-gui/issues/654

**Comment by jytou** [comment]
Just double-check how you close storjshare. If you close it with the X icon rather than the menu, you are probably in that situation: https://github.com/Storj/storjshare-gui/issues/746

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
