### ISSUE TITLE
UI/UX Wishlist (Time Check)

### ISSUE THREAD

**Issue by jflowers1974** [storj/storjshare-gui#650]
### Versions

- **GUI Version:** v6.2.0
- **Operating System:** Ubuntu 16.04.2 LTS

### Expected Behavior

Running the GUI - it would be nice if it would do some ENV checks.  After playing about, I realized that I needed to fix the time server.  Shouldn't the software throw an error if it detects an error with the time/or lack of configuration of a time server?

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
