### ISSUE TITLE
StorjShare can't understand NTFS drives mounted as a folder.

### ISSUE THREAD

**Issue by BikeHelmet** [storj/storjshare-gui#660]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.4.0

- **Operating System:** Windows 7 x64

### Expected Behavior

Please describe the program's expected behavior.

It saves up to the amount set in its config file in the storage location.

### Actual Behavior

It says there are 0 bytes free, indicating failure to understand mount points on Windows.

### Steps to Reproduce

Mount an NTFS drive to a folder. Try to point StorjShare to that folder for storing data.
### Screenshots (Optional)

![storjshare struggling with mount points](https://user-images.githubusercontent.com/8405847/28743449-e90e8e50-73fe-11e7-9470-3bd43d40dfad.png)

**Comment by littleskunk** [comment]
Please execute `wmic logicaldisk get size,freespace,caption` and show us the result.

**Comment by BikeHelmet** [comment]
wmic logicaldisk get size,freespace,caption
Caption  FreeSpace     Size
C:       90514821120   150323851264
S:       399935041536  1500299390976

**Comment by littleskunk** [comment]
and which folder did you select?

**Comment by BikeHelmet** [comment]
S:\STORJ\MOUNT_4TB_A\ which is a 4TB NTFS drive.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
