### ISSUE TITLE
Storj Share Gui only starting in background

### ISSUE THREAD

**Issue by Thyruz** [storj/storjshare-gui#663]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.4.0
- **Operating System:** Windows 10

### Expected Behavior

Please describe the program's expected behavior.

Sarting normally and opening the user interface

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Program starts only in the background (can be seen in task manager) but the user interface doesnt open.

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...Install
2. ...open Storj Share.exe
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
The first run will take a moment. Just wait a few minutes.

**Comment by Thyruz** [comment]
Thanks for the suggestion, but sadly it didnt help.

I let the program run for almost 3 hours without a result.

Still there is the process running on the background but no interface

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
