### ISSUE TITLE
unknown error, scandir

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-gui#671]
### Versions

Replace the values below with your own:

- **GUI Version:** latest
- **Operating System:** windows

### Expected Behavior

Please describe the program's expected behavior.

```
No error
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
Node will not start 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

![drive e -storj1 error](https://user-images.githubusercontent.com/11735738/29241548-d73660ec-7f73-11e7-9000-73db2dfc95af.png)

**Comment by aleksandrguru** [comment]
unknown: unknown error, scandir 'g:\sj3\sharddata.kfs'

**Comment by Coolestcool** [comment]
i have the same error  as aleksandrguru

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
