### ISSUE TITLE
Need to be able to specify a list of greylists

### ISSUE THREAD

**Issue by gilescope** [storj/storjshare-gui#687]
At the moment you can't specify the greylists through the gui. 

Distributed storage is a great idea, but people storing things need to be able to indicate what they do not want stored.

Better to do the dev now before you get a bad name and your distributed service abused. After a 'working' product this *must* be your highest priority.

**Comment by tempestb** [comment]
Data is encrypted and sharded, so the farmer never knows what he has.  There is no way to know.  Since data is encrypted at the client, only the renter knows what he uploaded.  The farmer has a chunk of the file that is scrambled and resembles nothing.

**Comment by gilescope** [comment]
Are we saying that greylisting just isn't feasable on the platform?

**Comment by tempestb** [comment]
What I'm saying is, what is it that you are trying to greylist?  Are you saying that you don't want video files or a specific music file or image?  It can't be done because you (as the farmer) have no idea what was uploaded.  Only the renter knows what he uploaded.  Nothing in the system has any knowledge of what the file is that was uploaded.  It's unique, it's encrypted, it's impossible to tell.

Until you unencrypt the file, the file shards are a jumbled mishmash of nothing data.  You are hosting pieces of encrypted data, that's it.  Only the renter can reconnect these pieces and produce a file.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
