### ISSUE TITLE
Changes in Config File arent updated in the GUI until complete Restart

### ISSUE THREAD

**Issue by stefanbenten** [storj/storjshare-gui#702]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.0.2
- **Operating System:** Windows Server 2016, 2012 R2 and Windows 10

### Expected Behavior

If the node is shut down and some changes are made to the config eg. Move of the data ord log folder, after starting the node the GUI should show the actual used values.

### Actual Behavior

If the mentioned steps are followed, the old values are shown and are not updated correctly.
A Fix is to restart the complete GUI, which leads to downtime of all nodes!

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Stop Node
2. Change Config Values eg. Log or Storage Path
3. Start Node

### Screenshots (Optional)

Can be done if needed.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
