### ISSUE TITLE
"Bridge" filed says "connected" when node is "OFF"

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-gui#703]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.0.2
- **Operating System:** windows 10
### Expected Behavior

Please describe the program's expected behavior.

```
Text should go to gray and "not connected"  (something like that).
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
GUI displays "Bridge" -> connected even though the node is "OFF".
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![bridge_field_issue](https://user-images.githubusercontent.com/11735738/30830452-65e4108a-a244-11e7-9e6c-0294087ef013.png)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
