### ISSUE TITLE
wrong free Diskspace usage node disapearing reentering node after Update

### ISSUE THREAD

**Issue by Luxi84** [storj/storjshare-gui#704]
### Versions

- **GUI Version:** v7.1.0
- **Operating System:** Xubuntu 16.04

### Expected Behavior

use almost full free diskspace reediting JSON to use free+used from Node
or use free Diskspace

### Actual Behavior

Message Invalid Storage Size
there are free 8473 GB Node what disapeard uses 300 GB so usable should be 8773 GB (with reediting)
over 8000 GB results in "invalid Storage Size"
-> Node disapears or doesent start

**Comment by littleskunk** [comment]
Confirmed. GUI doesn't like 8TB.

**Comment by mstuehlinger** [comment]
The limit per node is 8TB or 8192GB or 8388608MB or 8589934592KB or 8796093022208B.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
