### ISSUE TITLE
Full node will not connect

### ISSUE THREAD

**Issue by bomboflogic** [storj/storjshare-gui#709]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.1.0
- **Daemon Version:** v5.1.0
- **Core Version:** v8.1.0
- **Protocol Version:** v1.2.0
- **Operating System:** Windows 10 64-bit

### Expected Behavior

Node reaches 100% allocation size threshold and should stay connected and reachable by the network.

```

```

### Actual Behavior

Node reaches 100% allocation size threshold and does not connect, is not reachable by the network.

```

```

### Steps to Troubleshoot

1. Closed Storj, Updated to newest version, opened Storj
2. Lowered the allocation size of the node by a small size, closed Storj, opened Storj
3. Lowered the allocation size of the node by 50%, closed Storj, opened Storj

**Comment by littleskunk** [comment]
Tested with GUI 7.1.0 on windows 10 64bit. Sorry that is not the reason for your problem. I reduced my allocated size to 100Bytes. My farmer is connecting fine but will not send any OFFER. I added `"spaceAvailable": false` to my logfile. My farmer is connecting fine and updating my contact information on the bridge.

How about logfiles?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
