### ISSUE TITLE
Better tooltips

### ISSUE THREAD

**Issue by tempestb** [storj/storjshare-gui#722]
I am going to work on this today, but figured I'd create the issue here and then tag the PR when it's ready to go.

  I'm going to update the tooltips in the index.js to better explain what each piece means as to improve user understanding and reduce Q&A in rocketchat.

Thanks
Kevin

**Comment by littleskunk** [comment]
Pull request merged. Anything else or close this issue?

**Comment by ordtrogen** [comment]
Please make tooltips fit the screen. See example

![tip1](https://user-images.githubusercontent.com/15184875/32154634-319165fe-bd32-11e7-869f-9004b977ec4f.png)

**Comment by ordtrogen** [comment]
The column already says "Node ID", how is it helpful in the tooltip to repeat that? 

![tip3](https://user-images.githubusercontent.com/15184875/32154816-8d0f1a88-bd33-11e7-9836-b4bdc9ae1b93.png)

**Comment by ordtrogen** [comment]
Something off with the wording. The "It is" doesn't make sense, does it?

![tip4](https://user-images.githubusercontent.com/15184875/32154861-eeefa75e-bd33-11e7-8ef5-38a702ae8ee7.png)

**Comment by tempestb** [comment]
Added suggested fixes to #729

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
