### ISSUE TITLE
Error when trying to edit drives

### ISSUE THREAD

**Issue by DSchaedler** [storj/storjshare-gui#725]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.1.0
- **Operating System:** Windows 10 Home N

### Expected Behavior

Please describe the program's expected behavior.

```
Clicking edit in a drive's menu provides some sort of interaction to change share settings.

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```

System error occurs, "This file does not have a program associated with it for preforming this action."

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Create a drive in the Storj application
2. Properly connect the drive to the network
3. Use the "Edit" button in the drive's drop-down menu

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 

![image](https://user-images.githubusercontent.com/20712246/31944807-4fcb5b92-b89b-11e7-9b93-f181bb654278.png)

**Comment by debarko** [comment]
This is most likely that the editor that is trying to open the file is having some issue. Storj suggests installing notepad++

> For windows users it is advisable to download and install notepad ++

Install it and set the default file allocation of json to notepad ++. It should start working.

**Comment by JacksonML** [comment]
I'm pretty sure this error is saying that there is no program associated with editing/opening json files. Maybe there's a way we could catch this and alert the user that they need to install something like notepad++. 

Opening in standard notepad shows me this which probably isn't the best way to view the config, but maybe its enough for what we need. Alternatively, the installer adds a file type association with .json and notepad.
![image](https://user-images.githubusercontent.com/6219290/32305599-d1348fac-bf4c-11e7-99f0-8494314626ed.png)
Edit action:
https://github.com/Storj/storjshare-gui/blob/ae271f8e4774bf364e3cbb3003dfcbc40b09cf92/app/stores/share_list.js#L288
[`shell.openItem` documentation](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenitemfullpath)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
