### ISSUE TITLE
.deb missing dependencies

### ISSUE THREAD

**Issue by fdawg4l** [storj/storjshare-gui#731]
The deb that is being published on https://github.com/Storj/storjshare-gui/releases/ for amd64 is missing dependencies.  Also it'd be great to publish a deb that didn't require a gui.

### Steps to Reproduce
```
dpkg -i <path to deb>
~# ldd /opt/storjshare/storjshare  | grep -i "not found"
	libXtst.so.6 => not found
	libXss.so.1 => not found
	libgconf-2.so.4 => not found
	libnss3.so => not found
	libnssutil3.so => not found
	libsmime3.so => not found
	libnspr4.so => not found
	libasound.so.2 => not found
```

**Comment by AlexeyALeonov** [comment]
on Ubuntu 17.10 version 7.3.4
sudo dpkg -i ./storjshare-gui.amd64.deb
```
$ /opt/storjshare/storjshare
/opt/storjshare/storjshare: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
