### ISSUE TITLE
Error: EBUSY: resource busy or locked, open 'C:\Users\...\nodeid_date.log'

### ISSUE THREAD

**Issue by starrychloe** [storj/storjshare-gui#732]
### Versions

- **GUI Version:** GUI 7.2.0
- Daemon 5.2.0
- Core 8.4.2
- Protocol 1.2.0

- **Operating System:** Windows 8.1

### Expected Behavior

I expect it never to crash.

### Actual Behavior

It crashed. 

The log file is freaking 2MB! https://gist.github.com/starrychloe/19a542635a8c8f76d5f2dfff16406f12

### Steps to Reproduce

1. Run STORJ
2. Wait

### Screenshots (Optional)

![image](https://user-images.githubusercontent.com/1039276/32418064-ce671b5a-c230-11e7-8c5c-8355cdf28f7a.png)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
