### ISSUE TITLE
integrated light ETH wallet and hardware profit statistics and calculations. - fetcher improvement -

### ISSUE THREAD

**Issue by Patrick-W-McMahon** [storj/storjshare-gui#734]
This is a fetcher Improvement from a team that is evaluating a massive server farm
--------------------------------------------------------------------------------------
built in thin client ETH wallet. On setup it can create a ETH wallet for you or you can enter your ETH wallet.
This built in thin client ETH wallet will have the Storj preset. Transaction UX to show payouts, so people don't need to keep going to the chat rooms asking for when the payout is going to happen. 
live payment statistics in the UX. As the nodes run show live calculated profits. Numbers will change over the month and users know it will change as more data is collected. 
- Current calculated profites
- Expected payout
- Expected payout date
- Max calculated possible payout for configuration (how much the system can produce at max load, fully filled).

Every system running the storj client currently must have one CPU per node so we already know anyone running the storj client has a very powerful computer. The client has the resources to make estimates on profit based off its usage. It would be great to have a UX that can manage multiple computers in a network. Farmers will run more than one computer.

**Comment by kadamwolfe** [comment]
> Every system running the storj client currently must have one CPU per node so we already know anyone running the storj client has a very powerful computer.

That's a pretty big assumption.  I'd wager that a lot of people are pulling this off using Raspberry Pis and similar devices.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
