### ISSUE TITLE
Number of peers drops to very low values through time

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/storjshare-gui#738]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.7.0
- **Operating System:** windows

### Expected Behavior

Please describe the program's expected behavior.

```
Number of peers stays high
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The number of peers keeps dropping though time to very low levels.

```
For more info please contact @zerf and @AdrianoEcker on rocketchat

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

[node and daemon logs.zip](https://github.com/Storj/storjshare-gui/files/1510998/node.and.daemon.logs.zip)

![clipboard - november 28 2017 11_29 am](https://user-images.githubusercontent.com/11735738/33334860-abe4c5d0-d46b-11e7-9c16-761e70658b8c.png)

**Comment by botdruff** [comment]
I noticed this issue on my raspi3 node too both yesterday and today. I haven’t seen that issue appear before those two times though.

**Comment by Skippydog** [comment]
I am also seeing peers drop over time pretty heavily. Seems to be something new I have been seeing. 6 servers running between 1 and two nodes each. In 3 different geo-locations. On different operating systems and a few different firewalls as well a direct public connected system. Seems like something has changed recently.  I am seeing peers go down to 35 or less and stay down until i restart daily.  Restart and im up to 170.  Hopefully, this is expected behavior.
I have been doing a daily restart to resolve the issue 😞

**Comment by clexanis** [comment]
# **Versions**

daemon: 5.2.0, core: 8.4.2, protocol: 1.2.0
node v6.11.5
Debian 8.9
Kernel 4.9.0-0.bpo.4-amd64

# **Expected Behavior**

Number of peers stays high, and shards comming.

# **Actual Behavior**

The number of peers keeps dropping though time to very low levels (~100 after 1 day and <50 after 3 days), and shards stop coming.

# **Steps to Reproduce**

Start a share

# **Screenshots**

![putty_2017-11-26_13-14-24](https://user-images.githubusercontent.com/29154441/33342944-015ce3e0-d484-11e7-91db-f369987d839a.png)

# **Logs**

[logs.zip](https://github.com/Storj/storjshare-gui/files/1511544/logs.zip)

Original message :

>  Hello,
> 
> My problem is, after some time, the amount of peers keep lowering (150 at launch, ~100 after one day, and can be <50 after a few days).
> The problem as appeared after a two week of running without issues.
> 
> I tried with and without NAT traversal strategies, without mergerfs (where the files are), and have checked that the router is still configured to redirect connections.
> 
> Thanks in advance.

**Comment by littleskunk** [comment]
This is a side effect of SIP6 and nothing to worry about.

The old implementation was using PUBLISH messages to send out new contracts. Without any peers the farmer was not receiving any PUBLISH messages. This will trigger a network rejoin. New peers will be discoveres.

The new SIP6 implementation is working different. The farmer will receive ALLOCs even with 0 peers. As long as the farmer is receiving any messages network rejoin will not be triggered.

**Comment by NATEWONGCHOERIS** [comment]
why I even do not have a peer? sometimes it shows 1 and most time its 0.
