### ISSUE TITLE
Can website/app add foreign language?

### ISSUE THREAD

**Issue by hashday** [storj/storjshare-gui#750]
### Language （语言）

The language I need is Chinese. （我需要的语言是中文）
It has two branches： （它包含两种分支：）

- **Simplified Chinese:** 简体中文
- **Traditional Chinese:** 繁体中文

### The Reasons for Adding it （添加的原因）

Storj is a high - rising blockchain service, but it doesn't have a large number of Chinese users. There are 1 billion 400 million people in China and 750 million of China's Internet users. There is a large part of the bitcoin mining hash in Chinese, which also makes China bitcoin traders bitcoin prices have a significant impact. So this is a huge market. Adding Chinese interface will bring a large number of miners and consumers to Storj, and also solve the language barriers of Chinese players who want to join Storj now.
（Storj是一个上升空间很高的区块链服务，但是它却没有大量的中国用户。中国有14亿人口，中国网络用户有7.5亿。比特币的挖矿有很大一部分算力在中国，这也使得中国比特币交易者对比特币的价格产生重大的影响。因此这是一个巨大的市场，增加中文界面将为Storj带来巨大数量的矿工与消费者，同时也解决了目前希望加入Storj的中国玩家的语言障碍。）

### Implementation （实施）

I have personally translated the front-end content of the home page(index.html)
Url：http://www.deityfile.com/storj.io/
（我个人已经翻译了首页(index.html)的前端内容，
链接：http://www.deityfile.com/storj.io/ ）

### Hope （希望）

I sincerely hope that Storj can open up a huge market in China network, and also hope that the Chinese users in the circle will share experience and promotion together.
（衷心希望Storj能够在中国网络开拓巨大市场，同时也希望圈内的中国用户一起分享经验与推广。)

### Other Language （其他语言）

In addition to Chinese, we hope to have other languages that are generally supported by the current blockchain trading centers.
（除了中文，我们希望能拥有现在区块链交易平台一般支持的其他各国语言。）

- **Donation:** 0x397a880d64e979f8cdb513eff948191b08a660e5
- **捐赠地址:** 0x397a880d64e979f8cdb513eff948191b08a660e5

**Comment by GoopyAspirin** [comment]
Hello. Happy New Year!
早安。 新年快乐！

I do not have much to do with the issues you have opened, but I would like to ask.
http://www.deityfile.com/storj.io/
I am wondering how to translate your linked index file into another language.
我没有太多关于你已经打开的问题，但我想问。
http://www.deityfile.com/storj.io/
我想知道如何将您的链接索引文件翻译成另一种语言。

If I search Google for a keyword, will the tutorial come up?
如果我在Google上搜索关键字，该教程会出现吗？

I hope this coin is widely known and developed.
我希望这枚硬币广为人知和发达。

=============

I think, the developer seems to have not considered it right now about adding another language.
我想，开发者似乎还没有考虑添加另一种语言。

If you add a language-related folder or the developer modifies some language frameworks and commits it,
如果您添加语言相关的文件夹，或者开发人员修改了某些语言框架和提交，多语言用户将能够自行修改语言。

**Comment by stefanbenten** [comment]
@hashday This issue isnt related to the GUI of the Software. 
You can open an issue here: https://github.com/Storj/storj.io/ or ask in the Community Chat over at https://community.storj.io/channel/local/.

Thanks!

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
