### ISSUE TITLE
Can I participate in multilingual translation?

### ISSUE THREAD

**Issue by GoopyAspirin** [storj/storjshare-gui#751]
I am interested in block chains.

Very good at Korean. (EN <-> KR)

This technology should be especially famous in Korea.
The cost of storing distributed storage in Korea is too expensive, and many people do not know this technology.

If we release and promote this program in Korean, we will have a lot of users.

I would like to participate in Korean translation.
If possible, add a source for the translation.
I will request a pull.

**Comment by hashday** [comment]
새해 복 많이 받으세요~
I agree with the translation plan!
Lets make Storj more and more internatinal~
——A Chinese miner

zh-CN : https://github.com/Storj/storjshare-gui/issues/750

**Comment by GoopyAspirin** [comment]
Thanks bro.

I have confirmed that there is a GUI language in the path below.

/storjshare-gui-master/app/lib/menu.js

How do I edit this file to add Korean?

Do you want to simply change the original file to Korean?
Or, modify menu.js to en-menu.js
Add new ko-menu.js?

Please tell us your acceptance criteria.

**Comment by GoopyAspirin** [comment]
Oh, and the storj.io site also needs translation.

Really. You can translate Korean fluently and naturally.

Please leave. I do not know. I will also leave an issue in storj.io Repo.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
