### ISSUE TITLE
Gear controls is not visible due to wide UI

### ISSUE THREAD

**Issue by wivern-co-uk** [storj/storjshare-gui#756]
### Versions

- **GUI Version:** 7.3.2
- **Operating System:** MacOS 10.13.3

### Expected Behavior

UI have to fit the most of screens - max 1280px wide
Gear icon should be visible without horizontal scrolling

### Actual Behavior

Current UI is more than >1500px wide which makes controls hard to spot for new customers 

### Steps to Reproduce

1. Install application on **laptop**
2. Run application
3. Add drive
4. Observe UI and see gear icon is not visible

### Screenshots (Optional)

[https://jumpshare.com/v/zTW7cGjJKVTcpJoNHbAx](https://jumpshare.com/v/zTW7cGjJKVTcpJoNHbAx)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
