### ISSUE TITLE
Sometimes the storj node restarts after that the already used HDD space shown in Shared stuck at ...

### ISSUE THREAD

**Issue by jensamberg** [storj/storjshare-gui#768]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.3.4
- **Operating System:** Ubuntu 16.04

### Expected Behavior

Please describe the program's expected behavior.

After a restart of Storj Gui or the nodes in the GUI I expect that the used disk space is shown under Shared

### Actual Behavior

Sometimes after a noder restart or manual restart already presented used disk space will be ...

After 2 up to 3 manual restarts the correct used disk space is presented again correct.

### Steps to Reproduce

Actial no straight forward steps for reproduction

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot. 
![54998c0c-4ca8-43d4-ba42-2eb2a8d82679](https://user-images.githubusercontent.com/22682327/39540576-50d71c04-4e43-11e8-9dcc-3ecc74507195.jpeg)
![4e6bda5b-7314-4f19-8a61-15aa905a1c17](https://user-images.githubusercontent.com/22682327/39540577-5108de88-4e43-11e8-982a-9b1c46c47dd7.png)

**Comment by jensamberg** [comment]
Here is the picture with the issue
![bb08a8d4-3c00-4c46-84b0-10598501f9f5](https://user-images.githubusercontent.com/22682327/39541690-c867c310-4e46-11e8-953c-dec03cdc619f.jpeg)

**Comment by nerdatwork** [comment]
How to fix the corrupted database:
1. install the node.js LTS version: https://nodejs.org/en/download
2. run in command line (cmd/powershell): `npm install -g kfs@v3.0.0`
3. stop the node
4. in the command line (cmd/powershell): `kfs -(your driveletter) c:\your path\sharddata.kfs compact

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
