### ISSUE TITLE
Storjshare icon for program disappears in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by smkm** [storj/storjshare-gui#771]
#### Versions

- **GUI Version:** v7.3.4 (latest as of April)
- **Operating System:** Ubuntu 18.04 with the default Ubuntu Gnome Desktop Environment

#### Expected behaviour

When the Storjshare program is executed, the program should show the normal Storj icon like ![img](https://i.imgur.com/DUsvKRA.png) (Image property of Storj Labs Inc.). Also, a button with the Storj icon, showing that Storjshare is currently executing, should be shown on the tray bar.  

#### Actual behavior

![img](https://i.imgur.com/Z4B4OGj.png)  
![img](https://i.imgur.com/OKtteq9.png)  
Like the above images, the icons show an error. Also, the icon on the taskbar, which has a function of showing the users whether Storjshare is operating, does not show at all, like the image below. Therefore, for sure, this is not a simple cosmetic issue for users experiencing this error.   
![img](https://i.imgur.com/tfI5R0k.png)  

#### How to reproduce  
In Ubuntu 18.04, install [storjshare-gui.amd64.deb](https://github.com/storj/storjshare-gui/releases/download/v7.3.4/storjshare-gui.amd64.deb) with the command `sudo gdebi storjshare-gui.amd64.deb` or using any other package manager. Execute the Storjshare program, and look at the task bar. Ubuntu 18.04 users may experience this error.   

#### Recording Of The Bug (Screenshots)  

![img](https://i.imgur.com/Z4B4OGj.png)  
![img](https://i.imgur.com/OKtteq9.png)  
![img](https://i.imgur.com/tfI5R0k.png)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
